version: '3.1'

networks:
  columbus-net:
    driver: bridge

services:
  columbus-api:
    build: 
      context: ./
      dockerfile: Dockerfile.local    
    networks:
      - columbus-net
    ports:
    - '85:8000'
    restart: always
    environment:
    - WEB_CONCURRENCY=5